"""Type stubs for fastapi.testclient — covers only the API surface used by arxivsmart tests."""

from typing import Any

import httpx
from fastapi import FastAPI

class TestClient:
    def __init__(self, app: FastAPI, **kwargs: Any) -> None: ...
    def get(self, url: str, **kwargs: Any) -> httpx.Response: ...
    def post(self, url: str, **kwargs: Any) -> httpx.Response: ...
    def put(self, url: str, **kwargs: Any) -> httpx.Response: ...
    def delete(self, url: str, **kwargs: Any) -> httpx.Response: ...
